### ISSUE TITLE
BarLeft, contexts and stores

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-bar#144]
Since we render `<BarLeft />`, `<BarRight />` inside the context of the bar, their context is changed and as such, some components using the redux store, will get the store of the bar instead of the one of their app. We can [use a trick and essentially bind the context](https://github.com/cozy/cozy-bar/blob/c0d08bf7796dfe79b328fbac8ab51760bbe5d775/README.md#customizing-the-content-of-the-bar) to the component but I think it should be easier to do than that. I suggest to use a different `storeKey` for the bar store : https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by y-lohse** [comment]
I wasn't aware of the `storeKey`, it indeed looks like the way to go!

**Comment by y-lohse** [comment]
I've renamed the issue for something thats hopefully clearer, as I missed the issue and recreated #241 instead.

Over there, we suggested 2 more solutions:

- Using portals (who preserve the correct context) to render the components in the main app, and portaling them into the bar
- Providing a new context inside the `BarLeft` to avoid using the one from the bar

### 1. Using a different `storeKey``

Sadly that didn't work at all. If you're interested, [here's a commit that makes the cozy-bar use a different store key](https://github.com/y-lohse/cozy-bar/commit/0212c164501cc8c120d1d1f6844e05f486aa2e2d).

`storeKey` is good when you have multiple stores inside the same app, something like this:

```
<Provider store={MyFirstStore}>
  <Provider store={MySecondStore}>
    <MyComponent />
  </Provider>
</Provider>
```

If `MyComponent` needs something from the first store it wouldn't work, unless you use `storeKey`. But in our case, we have something like this:

```
<Provider store={AppStore}>
</Provider>
<Provider store={BarStore}>
  <MyComponentWantsSomethingFromAppStore />
</Provider>
```

Even if it worked, we'd only get the correct store — anything connected to redux would work, but that's it (no translations for example).

### 2. Portals

Didn't work for us, although I'm less sure why. We randomly have errors about preact that can't read parentNode` of `null`, even without using `BarLeft`. But even when these errors go away, the potaled content simply doesn't show up.

If someone else runs into this issue, I still think it should work *in theory*.

### 3. Providing a context

Not exactly sure what @ptbrowne meant with `ContextProvider`, but that did work for us. You can't use the new Context API because redux & co don't get their store from there, but you *can* create a provider that uses the old API — see [this commit](https://github.com/y-lohse/cozy-drive/commit/45d405c40b7833bb4cd698347c13b758d081dcc4#diff-d35b90229054f06f8be4bbc3d6a0a652R29).

Pretty sure this should be illegal, but it's the only thing that I got working. It allows us to do [this](https://github.com/y-lohse/cozy-drive/commit/45d405c40b7833bb4cd698347c13b758d081dcc4#diff-d35b90229054f06f8be4bbc3d6a0a652R118):

```
<BarRight>
    <BarContextProvider
      client={this.context.client}
      store={this.context.store}
      t={this.context.t}
    >
        {MoreMenu}
      </BarContextProvider>
    </BarRight>
```

I wonder if we could add this to the `BarXXX` API. Something like this maybe:

```
<BarLeft context={{ store: myStore, t: myTranslationFunc }}>
  <CustomBarContent />
</BarLeft>
```

Does that inspire anyone? Should we make a PR to add this to the cozy-bar?

**Comment by ptbrowne** [comment]
BarLeft saves its children in the store of the bar. So when you do : 

`<BarLeft><Toto /></BarLeft> -> store.set('left', <Toto/>)` (pseudocode)

I think BarLeft could save its context in the store.

`store.set('left', { component: <Toto/>, context: this.context })`

and then in the `<Bar />` we could pass this context down via a ContextProvider.

We also have to keep in mind that with React, it is compulsory to tell React each context prop that will be passed down via `childContextTypes`.

**Comment by ptbrowne** [comment]
When needing client / store / i18n context inside components that are in the bar, you can use https://github.com/cozy/cozy-ui/tree/master/react/BarContextProvider
